global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nextjs'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/api/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['turbo-25-redis:6379']