[install]
command = "pnpm install"

[build]
builder = "nixpacks"
buildCommand = "cd apps/queue-workers && pnpm run build"

[deploy]
startCommand = "cd apps/queue-workers && pnpm run start:prod --silent"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10