[install]
command = "pnpm install"

[build]
builder = "nixpacks"
buildCommand = "pnpm run build:queue"

[deploy]
startCommand = "pnpm run start:queue"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10