providers = ["node"]

[phases.install]
cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@9.1.0 --activate", "pnpm install"]

[build]
builder = "nixpacks"
buildCommand = "pnpm build:queue"

[deploy]
startCommand = "pnpm start:queue"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10