[install]

command = "pnpm install"
[build]
builder = "nixpacks"
buildCommand = "pnpm build:queue"

[deploy]
startCommand = "pnpm start:queue"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10