
[phases.install]
    cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@9.1.0 --activate", "pnpm install"]

[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build:queue"

[deploy]
startCommand = "pnpm start:queue"
healthcheckPath = "/"
healthcheckTimeout = 100

[build.env]
NODE_ENV = "production"