import type { Metadata, Viewport } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { AuthProvider } from '@/features/auth/providers/auth-provider'
import { ThemeProvider } from '@/features/theme/providers/theme-provider'
import { RouteProgressBar } from '@/features/navigation/components/route-progress-bar'

import { themes } from '@/features/theme/config/themes'

export const viewport: Viewport = {
  themeColor: [
    ...themes.map((theme) => ({
      media: `(prefers-color-scheme: ${theme.id})`,
      color: theme.themeColor,
    })),
  ],
}

console.log('viewport', viewport)

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <AuthProvider>
            <RouteProgressBar />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
